name: ankole_fresh
description: A fresh produce delivery mobile application for Ankole Fresh Ltd
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  # Essential packages
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  shimmer: ^3.0.0
  
  # NEW packages to add
  flutter_staggered_grid_view: ^0.7.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/